analyzer_rules:
  - unused_import
  - unused_declaration

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean  
  - empty_count
  - empty_string    
  - explicit_init
  - fatal_error_message
  - file_length
  - first_where
  - force_cast
  - force_try
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - modifier_order
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension    
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last  
  - switch_case_on_newline
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

line_length: 160

function_body_length: 80

line_length: 180

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage

custom_rules:
  quickspec_class_name:
    name: "Invalid Test Class Name"
    regex: "class\\s+(.*)[^Tests]:\\s+QuickSpec"
    message: "A test class name must end with 'Tests'"
    severity: error

reporter: "xcode"      
