# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'AKSideMenuStoryboard' do
  pod 'AKSideMenu', :path => '../../AKSideMenu.podspec'
end