name: Building
on: [push, pull_request]

jobs:
  build:
    name: Building AKSideMenu Example
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_$(cat .xcode-version).app
      
      - name: Install Dependencies for Simple Example
        run: |
          pod install --project-directory=AKSideMenuExamples/Simple
        shell: bash
      
      - name: Install Dependencies for Storyboard Example
        run: |
          pod install --project-directory=AKSideMenuExamples/Storyboard
        shell: bash        
      
      - name: Building iOS Simple app
        run: exec ./.github/scripts/build_app.sh simple
      
      - name: Building iOS Storyboard app
        run: exec ./.github/scripts/build_app.sh storyboard        
